// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotzkwelitlqbdzzolak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdHprd2VsaXRscWJkenpvbGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjMwODQsImV4cCI6MjA2MTA5OTA4NH0.5pHVJWfZDacubYCq3OEpJplh8E41bRjyHrjubI8k6RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);